name: Sync to Hugging Face spaces
on:
  push:
    branches: [main]
  # මේකෙන් කරන්නේ main branch එකට push කරන හැම වෙලාවකම sync කරන එකයි

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Remove notebooks directory
        run: |
          rm -rf notebooks/
          rm -rf .git  
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -A
          git commit -m "Sync to Hugging Face Spaces (excluding notebooks)" || echo "No changes to commit"
          git push --force https://Kavindu1124:$HF_TOKEN@huggingface.co/spaces/Kavindu1124/DeepScholar-AI main