name: Sync to Hugging Face spaces
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean History and Push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. notebooks folder එක මකන්න
          rm -rf notebooks/

          # 2. අලුතෙන් Git එකක් හදන්න
          rm -rf .git
          git init
          
          # 3. Branch එකේ නම 'main' කියලා වෙනස් කරන්න (මේක තමයි වැදගත්ම දේ)
          git checkout -b main
          
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 4. Files ඇඩ් කරලා commit කරන්න
          git add .
          git commit -m "Fresh sync to HF without large files"
          
          # 5. දැන් push කරන්න
          git push --force https://Kavindu1124:$HF_TOKEN@huggingface.co/spaces/Kavindu1124/DeepScholar-AI main